[theme]
primaryColor="#ffbdf9"
backgroundColor="#ffeffb"
secondaryBackgroundColor="#f991fd"
textColor="#060606"
font = "'Playfair Display':https://fonts.google.com/css2?family=Playfair+Display&display=swap"
